<!doctype html>
<html lang="fr"><head><meta charset="utf-8"><style>
@page { margin: 22px 24px; } body { font-family: DejaVu Sans, sans-serif; font-size: 8px; color: #202a33; }
.head { border-bottom: 2px solid #26343d; padding-bottom: 8px; }.title { text-align:center; font-size:14px; font-weight:bold; border:1px solid #26343d; padding:8px; margin:15px 0; }.section{margin-top:15px;page-break-inside:avoid}.section h2{font-size:9px;background:#e7ecef;padding:5px;margin:0;border:1px solid #9aa7b1}.table{width:100%;border-collapse:collapse}.table th,.table td{border:1px solid #9aa7b1;padding:4px}.table th{background:#edf1f3;font-size:7px}.right{text-align:right}.footer{position:fixed;bottom:-10px;left:0;right:0;border-top:1px solid #79848c;padding-top:5px;color:#66747d}.page:after{content:counter(page)}
</style></head><body>
@php($depots = $operations->filter(fn ($operation) => $operation->type->value === 'depot'))
<div class="head"><strong>FÉCECAM – BÉNIN</strong><span style="float:right">{{ $agence->nom }} · {{ $agence->code }}</span></div>
<div class="title">RAPPORT QUOTIDIEN D’ACTIVITÉ — {{ $debut->format('d/m/Y') }} AU {{ $fin->format('d/m/Y') }}</div>
<p>Agence : {{ $agence->nom }} · Opérations : {{ $statistiques['operations'] }} · Dépôts : {{ number_format((float) $statistiques['depots'], 0, ',', ' ') }} XOF · Retraits : {{ number_format((float) $statistiques['retraits'], 0, ',', ' ') }} XOF</p>
<div class="section"><h2>OPÉRATIONS INHABITUELLES / OCCASIONNELLES (MONTANT ≥ {{ number_format($seuilInhabituel, 0, ',', ' ') }} XOF)</h2><table class="table"><tr><th>Code client</th><th>Nom du client</th><th>Montant</th><th>Compte</th><th>Date</th><th>Transaction</th></tr>@forelse($operationsInhabituelles as $operation)<tr><td>{{ $operation->compte?->client_id }}</td><td>{{ $operation->compte?->client?->nomAffichage() }}</td><td class="right">{{ number_format((float) $operation->montant, 0, ',', ' ') }}</td><td>{{ $operation->compte?->numero }}</td><td>{{ $operation->effectuee_le->format('d/m/Y H:i') }}</td><td>{{ $operation->type->libelle() }}</td></tr>@empty<tr><td colspan="6">Aucune opération pour cette période.</td></tr>@endforelse</table></div>
<div class="section"><h2>OPÉRATIONS INHABITUELLES QUOTIDIENNES PAR COTATION</h2><table class="table"><tr><th>Code client</th><th>Nom du client</th><th>Compte</th><th>Dépôts quotidiens</th><th>Plafond quotidien (cotation)</th></tr>@forelse($depots as $operation)<tr><td>{{ $operation->compte?->client_id }}</td><td>{{ $operation->compte?->client?->nomAffichage() }}</td><td>{{ $operation->compte?->numero }}</td><td class="right">{{ number_format((float) ($depotParClient[$operation->compte_id] ?? 0), 0, ',', ' ') }} XOF</td><td class="right">{{ $operation->compte?->client?->identite?->plafond_quotidien_especes ? number_format((float) $operation->compte->client->identite->plafond_quotidien_especes, 0, ',', ' ').' XOF' : '—' }}</td></tr>@empty<tr><td colspan="5">Aucun dépôt pour cette période.</td></tr>@endforelse</table></div>
<div class="section"><h2>COMPTES DORMANTS RÉACTIVÉS</h2><table class="table"><tr><th>Code client</th><th>Nom membre</th><th>Compte</th><th>Date de réactivation</th></tr>@forelse($comptesDormantsReactives as $alerte)<tr><td>{{ $alerte->client_id }}</td><td>{{ $alerte->client?->nomAffichage() }}</td><td>{{ $comptesParId[$alerte->faits['compte_id'] ?? null]?->numero ?? '—' }}</td><td>{{ $alerte->created_at->format('d/m/Y') }}</td></tr>@empty<tr><td colspan="4">Aucun compte dormant réactivé.</td></tr>@endforelse</table></div>
<div class="section"><h2>OUVERTURES QUOTIDIENNES — PERSONNES PHYSIQUES</h2><table class="table"><tr><th>Code client</th><th>Nom et prénom</th><th>Compte</th><th>Date d’ouverture</th></tr>@forelse($clientsPhysiques as $client)<tr><td>{{ $client->id }}</td><td>{{ $client->nomAffichage() }}</td><td>{{ $client->comptes->first()?->numero }}</td><td>{{ $client->created_at->format('d/m/Y') }}</td></tr>@empty<tr><td colspan="4">Aucune ouverture pour cette période.</td></tr>@endforelse</table></div>
<div class="section"><h2>OUVERTURES QUOTIDIENNES — PERSONNES MORALES</h2><table class="table"><tr><th>Code client</th><th>Raison sociale</th><th>Compte</th><th>Date d’ouverture</th></tr>@forelse($clientsMoraux as $client)<tr><td>{{ $client->id }}</td><td>{{ $client->nomAffichage() }}</td><td>{{ $client->comptes->first()?->numero }}</td><td>{{ $client->created_at->format('d/m/Y') }}</td></tr>@empty<tr><td colspan="4">Aucune ouverture pour cette période.</td></tr>@endforelse</table></div>
<div class="footer">Généré par {{ $identite['nom_systeme'] }} le {{ now()->format('d/m/Y H:i') }} · Page <span class="page"></span></div></body></html>
