@extends('layouts.agent')

@section('titre', 'Rapports journaliers')
@section('sous-titre', 'Générez, téléchargez et partagez les rapports de votre agence.')

@section('contenu')
<style>
    .reports { font-family: 'Plus Jakarta Sans', sans-serif; color:#1e293b; }
    .report-hero { background:linear-gradient(135deg,#29323a,#40515d); border-radius:20px; padding:25px; color:#fff; margin-bottom:18px; display:flex; justify-content:space-between; gap:20px; align-items:center; }
    .report-hero h1 { margin:0; font-size:1.35rem; }.report-hero p { color:#d8e0e5; margin:7px 0 0; font-size:.82rem; }
    .report-grid { display:grid; grid-template-columns:repeat(4,minmax(0,1fr)); gap:13px; margin-bottom:18px; }.metric,.panel { background:#fff; border:1px solid #e5eaf0; border-radius:16px; box-shadow:0 6px 20px rgba(15,23,42,.04); }.metric{padding:16px}.metric span{display:block;color:#64748b;font-size:.72rem;font-weight:700}.metric strong{display:block;margin-top:6px;font-size:1.2rem}.panel{padding:20px;margin-bottom:18px}.panel h2{font-size:.95rem;margin:0 0 15px}.period-form,.share-form{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;align-items:end}.field{display:flex;flex-direction:column;gap:6px}.field label{font-size:.72rem;font-weight:800;color:#475569}.field input{border:1px solid #dce4ec;border-radius:9px;padding:10px;font:inherit;font-size:.8rem}.button{border:0;border-radius:9px;padding:11px 14px;text-decoration:none;cursor:pointer;font:inherit;font-size:.78rem;font-weight:800;text-align:center}.primary{background:#2c343d;color:#fff}.secondary{background:#f0e535;color:#27313a}.outline{background:#fff;color:#334155;border:1px solid #dce4ec}.chart-wrap{height:245px}.history{width:100%;border-collapse:collapse;font-size:.79rem}.history th,.history td{padding:12px 10px;border-bottom:1px solid #edf1f5;text-align:left}.history th{color:#64748b;font-size:.68rem;text-transform:uppercase}.actions{display:flex;gap:7px;flex-wrap:wrap}.share-form{grid-template-columns:2fr 2fr 2fr 1.2fr}.help{font-size:.72rem;color:#64748b;line-height:1.5;margin:10px 0 0}.report-card{display:grid;grid-template-columns:1.3fr 1fr;gap:18px}.alert{padding:12px 14px;border-radius:10px;background:#edf9ef;color:#187137;font-size:.8rem;font-weight:700;margin-bottom:15px}@media(max-width:900px){.report-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.period-form,.share-form,.report-card{grid-template-columns:1fr}}@media(max-width:520px){.report-grid{grid-template-columns:1fr}.report-hero{display:block}.report-hero .button{display:inline-block;margin-top:15px}}
</style>
<div class="reports">
    @if(session('statut'))<div class="alert">{{ session('statut') }}</div>@endif
    <section class="report-hero"><div><h1>Rapports d’activité sécurisés</h1><p>Format quotidien inspiré des bordereaux FÉCECAM : opérations, comptes réactivés et ouvertures.</p></div><a class="button secondary" href="#generation">Générer un rapport</a></section>
    <div class="report-grid">
        <div class="metric"><span>Opérations de la période</span><strong>{{ $donnees['statistiques']['operations'] }}</strong></div>
        <div class="metric"><span>Dépôts</span><strong>{{ number_format((float)$donnees['statistiques']['depots'],0,',',' ') }} XOF</strong></div>
        <div class="metric"><span>Retraits</span><strong>{{ number_format((float)$donnees['statistiques']['retraits'],0,',',' ') }} XOF</strong></div>
        <div class="metric"><span>Nouveaux clients</span><strong>{{ $donnees['statistiques']['clients'] }}</strong></div>
    </div>
    <section id="generation" class="panel"><h2>1. Choisir la période</h2><form class="period-form" method="GET"><div class="field"><label for="date_debut">Date de début</label><input id="date_debut" type="date" name="date_debut" value="{{ $debut->toDateString() }}"></div><div class="field"><label for="date_fin">Date de fin</label><input id="date_fin" type="date" name="date_fin" value="{{ $fin->toDateString() }}"></div><button class="button outline" type="submit">Appliquer le filtre</button></form><form method="POST" action="{{ route('agent.rapports.generer') }}" style="margin-top:12px">@csrf<input type="hidden" name="date_debut" value="{{ $debut->toDateString() }}"><input type="hidden" name="date_fin" value="{{ $fin->toDateString() }}"><button class="button primary" type="submit"><i class="fa-solid fa-file-pdf"></i> Générer le rapport de cette période</button></form></section>
    <section class="report-card"><div class="panel"><h2>Activité de la période</h2><div class="chart-wrap"><canvas id="operationsChart"></canvas></div></div><div class="panel"><h2>Contenu du PDF</h2><p class="help">• Opérations inhabituelles (seuil ≥ {{ number_format($donnees['seuilInhabituel'],0,',',' ') }} XOF)<br>• Dépôts par compte<br>• Comptes dormants réactivés<br>• Ouvertures personnes physiques et morales</p><p class="help">Les données sont limitées à votre agence et restent stockées dans l’espace privé de l’application.</p></div></section>
    <section class="panel overflow-x-auto"><h2>2. Rapports générés</h2><table class="history"><thead><tr><th>Période</th><th>Créé le</th><th>Statut</th><th>Actions</th></tr></thead><tbody>@forelse($rapports as $rapport)<tr><td>{{ $rapport->date_debut->format('d/m/Y') }} — {{ $rapport->date_fin->format('d/m/Y') }}</td><td>{{ $rapport->created_at->format('d/m/Y H:i') }}</td><td>{{ $rapport->envoye_le ? 'Envoyé de façon sécurisée' : 'Disponible' }}</td><td><div class="actions"><a class="button outline" href="{{ route('agent.rapports.telecharger',$rapport) }}">Télécharger</a><button class="button primary" type="button" onclick="document.getElementById('share-{{ $rapport->id }}').hidden = false">Envoyer</button></div></td></tr><tr id="share-{{ $rapport->id }}" hidden><td colspan="4"><form class="share-form" method="POST" action="{{ route('agent.rapports.envoyer',$rapport) }}">@csrf<div class="field"><label>E-mail du destinataire</label><input name="email" type="email" required autocomplete="email"></div><div class="field"><label>Code d’accès fort</label><input name="code_acces" type="password" required autocomplete="new-password" placeholder="12 caractères minimum"></div><div class="field"><label>Confirmer le code</label><input name="code_acces_confirmation" type="password" required autocomplete="new-password"></div><button class="button primary" type="submit">Envoyer le lien sécurisé</button></form><p class="help">Le destinataire reçoit un lien valable 7 jours. Il doit saisir ce code pour télécharger le PDF. Ne demandez jamais le mot de passe de sa messagerie.</p></td></tr>@empty<tr><td colspan="4">Aucun rapport généré pour le moment.</td></tr>@endforelse</tbody></table></section>
</div>
<script>new Chart(document.getElementById('operationsChart'),{type:'doughnut',data:{labels:['Dépôts','Retraits'],datasets:[{data:[{{ (float) $donnees['statistiques']['depots'] }},{{ (float) $donnees['statistiques']['retraits'] }}],backgroundColor:['#30c31a','#f0e535'],borderWidth:0}]},options:{maintainAspectRatio:false,plugins:{legend:{position:'bottom'}}}});</script>
@endsection
